// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUGTrmNEgGZxRkzNo17_MGhbvC5ATEzg',
    appId: '1:94348911367:web:09bc7b23b7a6fc5d9a9ba2',
    messagingSenderId: '94348911367',
    projectId: 'chatbot-5dc34',
    authDomain: 'chatbot-5dc34.firebaseapp.com',
    storageBucket: 'chatbot-5dc34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmYzW9k4h9j1e_D6r973jC6ugogd2ELkc',
    appId: '1:94348911367:android:dcec8339de9d84359a9ba2',
    messagingSenderId: '94348911367',
    projectId: 'chatbot-5dc34',
    storageBucket: 'chatbot-5dc34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0sllux6MWXXbof4PQbWXhLUfX1fL-0w',
    appId: '1:94348911367:ios:d21732f14682dbe69a9ba2',
    messagingSenderId: '94348911367',
    projectId: 'chatbot-5dc34',
    storageBucket: 'chatbot-5dc34.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0sllux6MWXXbof4PQbWXhLUfX1fL-0w',
    appId: '1:94348911367:ios:d21732f14682dbe69a9ba2',
    messagingSenderId: '94348911367',
    projectId: 'chatbot-5dc34',
    storageBucket: 'chatbot-5dc34.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBUGTrmNEgGZxRkzNo17_MGhbvC5ATEzg',
    appId: '1:94348911367:web:dfcd3f8fad0fb3499a9ba2',
    messagingSenderId: '94348911367',
    projectId: 'chatbot-5dc34',
    authDomain: 'chatbot-5dc34.firebaseapp.com',
    storageBucket: 'chatbot-5dc34.firebasestorage.app',
  );
}
